### ISSUE TITLE
Rotate by 12

### ISSUE THREAD

**Issue by will14smith** [guioconnor/ebg13#2]
I have an important business case to be able to rotate letters by a more secure number. 12 was chosen.

Please implement this.

**Comment by JMontagu** [comment]
This would break existing consumers -- this would have to be a v2 release. Maybe we could split out the core cipher and allow different rotation plugins to be injected?

**Comment by guioconnor** [comment]
Thanks for the feedback @will14smith, this has been on the roadmap for some time but now there is a compelling business case, I'll find time to do it.

As an aside, you won't be able to use Rot12 with a symmetric key, you'll need a 12/14 pair of keys to use this version of Rot. Or use Caesar's cypher in which you specify the direction the key needs to be applied.

**Comment by will14smith** [comment]
Thanks!

**Comment by guioconnor** [comment]
You are welcome @will14smith. NPM package being published as we speak.

**Comment by guioconnor** [comment]
And it is completely backwards compatible ;-)
